---
title: "Final_map_testing"
author: "Mike Wang"
date: "11/18/2019"
output: html_document
---

```{r}
library(readr)
library(tidyr)
library(tidyverse)
df=read.csv("~/Documents/STATW5702 Exploratory Data Analysis and Visualization/Final/Motor_Vehicle_Collisions_-_Crashes.csv")
df_filter = df
df_filter$year = substr(df$ACCIDENT.DATE, 7, 10)
df2015 = df_filter[df_filter$year == "2015",]
df2016 = df_filter[df_filter$year == "2016",]
df2017 = df_filter[df_filter$year == "2017",]
df2018 = df_filter[df_filter$year == "2018",]
df2017_18 = df_filter[(df_filter$year > "2016" & df_filter$year < "2019"),]

```

```{r}
library(lubridate)
library(ggplot2)
library(dplyr)
library(data.table)
library(ggrepel)
library(tidyverse)
library(ggmap)

#only keep the data with long and latitude not equal to NA
df2017_rm = df2017[complete.cases(df2017$LATITUDE), ]
df2017_rm = df2017_rm[as.numeric(df2017_rm$LONGITUDE) > -74.4, ]
df2017_rm = df2017_rm[as.numeric(df2017_rm$LONGITUDE)< -73, ]
p <- ggmap(get_googlemap(center = c(lon = -74.0797535, lat = 40.6969571),
                    zoom = 10, scale = 2,
                    maptype ='roadmap',
                    color = 'color'))
```
```{r, fig.width=8, fig.height=8}
p + geom_point(aes(x = LONGITUDE, y = LATITUDE), colour = "black", data = df2017_rm, alpha=0.1, size = 0.5) + 
  theme(legend.position="none")
```

```{r}
#contour map
p + 
  geom_density2d(data = df2017_rm, 
               aes(x = LONGITUDE, y = LATITUDE), size = 0.3) 
```
```{r}
p = p +coord_equal()

p + geom_hex(aes(x = LONGITUDE, y = LATITUDE,
                 fill = cut(..count.., c(0, 100, 250, 500, 1000,
                                         1500, 2000, 2500, Inf))), 
             colour = NA,
             data = df2017_rm, 
             alpha = 0.75, 
             bins = 50)+
    scale_fill_brewer(palette = "OrRd",
                      labels = c("<100", "100-250", "250-500",
                                 "500-1000", "1000-1500",
                                 "1500-2000", "2000-2500",
                                 ">2500")) +
  theme(legend.title=element_blank())+
  ggtitle("2017 collision count")

```
```{r}
df_vehical = df2017_18
df_vehical$VEHICLE.TYPE.CODE.1= toupper(df_vehical$VEHICLE.TYPE.CODE.1)
df_vehical = df_vehical %>%group_by(df_vehical$VEHICLE.TYPE.CODE.1)%>%summarise(total.count = n())
colnames(df_vehical) = c("Vehicle_Type", "Accidents")
df_vehical =mutate(df_vehical, Vehicle_Type = ifelse(Vehicle_Type =="", "N/A", as.character(Vehicle_Type)))

df_vehical = df_vehical[order(df_vehical$Accidents, decreasing = TRUE), ]


ggplot(aes(x = fct_reorder(Vehicle_Type, Accidents) , y=Accidents), data=df_vehical[c(1:20),]) +
  geom_bar(stat="identity")+ 
  coord_flip()+
  labs(x = "Vehicle Type", title = "2017 - 2018 top 20 Vehical Type for Collision")
```
```{r}
df_vehical2 = df2017_18
df_vehical2$VEHICLE.TYPE.CODE.1= toupper(df_vehical2$VEHICLE.TYPE.CODE.1)
df_vehical2 = mutate(df_vehical2, NUMBER.OF.PERSONS.INJURED = ifelse(is.na(NUMBER.OF.PERSONS.INJURED), 0, as.numeric(NUMBER.OF.PERSONS.INJURED)))
df_vehical2 = df_vehical2 %>%group_by(df_vehical2$VEHICLE.TYPE.CODE.1)%>%summarise(total.count = n(), NUMBER.OF.PERSONS.INJURED = sum(NUMBER.OF.PERSONS.INJURED))

```

